/*      File Name                Flash Index                   */
/*      ---------                -----------                   */
#define mainmenu                   0x20  /* File Size = 0x26A  */
/*      Arial_12.auf               0x21  /* File Size = 0x8C0  */
#define setupassay                 0x22  /* File Size = 0xFE   */
#define runassay                   0x23  /* File Size = 0x34F6 */
#define loadresults                0x24  /* File Size = 0xFE   */
#define debug                      0x25  /* File Size = 0x1742 */
/*      fonthdr.auf                0xF   /* File Size = 0x38   */
/*      internalram.bin            0x6   /* File Size = 0x214E */
